### PR TITLE
Fix: updated adwords ad performance adapter model

### PR DESCRIPTION
**Pull request by axelazaid**
* updated `adwords_ad_performance_adapter` to point to `adwords_url_performance` model
-- this will enable us to get the `url_host` and `url_path` associated with an adwords ad campaign
-- added missing fields

### CODE REVIEW

**Comment by jthandy** [comment]
@eogilvy12 I'd be interested to get your take here. I've started to do attribution work a little bit differently, and I'm interested in modifying the adwords package, in particular, to support this new understanding of how things should be done. The crux of the change would be no longer using GCLID and instead using the URL parameters in the final url report. This allows us to do some good things:

- it allows us to dynamically construct the `ad_performance_id` in the BI layer so that we can only join on the criteria we care about in a particular report and not overly limit.
- it allows us to remove the date from the `ad_performance_id` which forces us to cohort users on original ad impression date when we frequently don't want to produce our metrics like that.
- it creates consistency across all channels rather than having Google as a one-off that uses a different mechanism

I think the friction will be that some marketers don't have URL parameters, but that will be a struggle across channels in that case. Thoughts? Will this approach fail in the client scenarios you've seen?

**Review by drewbanin — DISMISSED** [review]
I can't speak to the logic change here, but nice work on switching the packages.yml file

**Review by drewbanin — COMMENTED** [review]
Oops, didn't mean to approve this

**Comment by eogilvy12** [comment]
@jthandy wanted to check back in on this - I think we should discuss in our conversation this afternoon!

**Comment by jthandy** [comment]
This is waiting on Alexa testing this on multiple different warehouses and ensuring that it works. I have no further PR comments on it, but we do need to make sure that it works on multiple adapters prior to merging. @axelazaid and I have spoken about this.

**Pull request merged**
